# Generated by Django 2.2.6 on 2019-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('pubdate', models.DateField()),
            ],
        ),
    ]
